package hirs.utils.signature;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.X509Certificate;

public interface SignatureFormat {

    /**
     * Creates a signature structure to be signed by a cryptographic engine.
     * @param signCert   X509 cert holding the SKID to use as the Key Identifier.
     * @param data Data to be signed
     * @return   Byte array holding the signed object.
     */
    public byte[] createToBeSigned(X509Certificate signCert, byte[] data) throws IOException, NoSuchAlgorithmException;

    /**
     * Adds a signature of the toBeSignedData to the Signature structure generated by a Cryptographic engine
     * @param signature
     * @return byte array holding the data to be signed by a crypto engine
     */

    public void addSignature(byte[] signature)  throws IOException;
    /**
     * Gets the signed data after the signature has been added
     * @return  byte array holding the signature structure with the payload, headers (if present), and signed data
     */
    public byte[] getSignedData() throws IOException;

}
