# Sets up and runs HIRS System tests

name: HIRS System Tests
on: 
  push:
    branches:
      - '*v3*'
      - 'main'
    workflow_dispatch:
env:
  TEST_STATUS: 0
jobs:
  DockerTests:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.set_outputs.outputs.test-result }}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> .ci/docker/.env
      id: branch_name
    - name: ACA TPM2 Tests
      continue-on-error: true
      shell: bash
      run: |
        # If on a forked repo, ensure that it has a new secret for the PAT
        # and replace secrets.PAT with the secret in the fork
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        bash .ci/system-tests/run_system_tests.sh
    - name: Archive System Test Log files
      uses: actions/upload-artifact@v3
      with:
        name: System_Test_Log_Files
        path: logs/
        if-no-files-found: ignore
    - name: Check System Test results
      if: success() || failure()
      run: |
        if [ ${TEST_STATUS} == "0" ]; then
          exit 0;
        else
          exit 1;
        fi
